/*
SQLyog Community
MySQL - 10.0.34-MariaDB-0ubuntu0.16.04.1 : Database - catv_monitor
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`catv_monitor` /*!40100 DEFAULT CHARACTER SET latin1 */;

USE `catv_monitor`;

/*Table structure for table `usuarios_mplay` */

DROP TABLE IF EXISTS `usuarios_mplay`;

CREATE TABLE `usuarios_mplay` (
  `MIBID` int(11) NOT NULL,
  `USERUNIQUEID` varchar(150) DEFAULT NULL,
  `USEREMAIL` varchar(150) DEFAULT NULL,
  `USERSTATUS` varchar(150) DEFAULT NULL,
  `TIPODOCUMENTO` varchar(10) DEFAULT NULL,
  `NUMERODOCUMENTO` int(8) unsigned zerofill DEFAULT NULL,
  `TELEFONO` int(11) DEFAULT NULL,
  `CREATIONDATE` varchar(20) DEFAULT NULL,
  `FLAGPRUEBA` varchar(10) DEFAULT NULL,
  `SUBSCRIPCIONES` varchar(30) DEFAULT NULL,
  `TIPOUSUARIO` varchar(30) DEFAULT NULL,
  `TIPOPRODUCTO` varchar(30) DEFAULT NULL,
  `TIPOCLIENTE` varchar(30) DEFAULT NULL,
  `PURCHASES` int(11) DEFAULT NULL,
  `VOD` int(11) DEFAULT NULL,
  `AUDIENCIAS_DECO` int(11) DEFAULT NULL,
  `AUDIENCIAS_MP` int(11) DEFAULT NULL,
  `CLUSTER_EPG_MPLAY` varchar(50) DEFAULT NULL,
  `N_DUPLICADO` int(11) DEFAULT NULL,
  PRIMARY KEY (`MIBID`),
  KEY `NUMERODOCUMENTO` (`NUMERODOCUMENTO`),
  KEY `TELEFONO` (`TELEFONO`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
